//! Assembling a monitor from a specification.

use crate::expr::{self, Lowering};
use crate::render;
use crate::{Error, Result, Settings};
use copilot_core::{Spec, StructType, Type};
use std::collections::BTreeMap;
use std::fmt::Write;

/// Emits every item of a monitor: struct types, the `Env` and `Handler` traits,
/// the state, and the step function.
pub fn items(spec: &Spec, settings: &Settings) -> Result<String> {
    copilot_core::validate(spec)?;
    check_names(spec)?;

    let mut out = String::new();
    let structs = collect_structs(spec)?;

    write_header(&mut out, spec, settings, &structs);
    write_structs(&mut out, &structs);
    write_env(&mut out, spec, settings);
    write_handler(&mut out, spec, settings);
    write_state(&mut out, spec, settings);
    write_step(&mut out, spec, settings);

    Ok(out)
}

fn write_header(out: &mut String, spec: &Spec, settings: &Settings, structs: &Structs) {
    let footprint = copilot_core::resources(spec);
    let counts = copilot_core::cost(spec);

    let _ = writeln!(out, "// Generated by copilot-rs. Do not edit.");
    let _ = writeln!(out, "//");
    let _ = writeln!(
        out,
        "// State: {} bytes, aligned to {}. Work per step: {} operations.",
        footprint.state_bytes, footprint.state_align, counts.nodes_shared
    );
    let _ = writeln!(
        out,
        "// Neither figure depends on how long the monitor has run."
    );
    if !structs.is_empty() || uses_math(spec) {
        let _ = writeln!(out, "//");
    }
    if uses_math(spec) {
        let _ = writeln!(
            out,
            "// Requires `{}` for the transcendental functions, which `core` does not provide.",
            settings.math
        );
    }
    let _ = writeln!(out);
}

fn write_structs(out: &mut String, structs: &Structs) {
    for definition in structs.values() {
        let _ = writeln!(out, "#[repr(C)]");
        let _ = writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq)]");
        let _ = writeln!(out, "pub struct {} {{", definition.name);
        for (field, ty) in &definition.fields {
            let _ = writeln!(out, "    pub {field}: {},", render::ty(ty));
        }
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }
}

fn write_env(out: &mut String, spec: &Spec, settings: &Settings) {
    let _ = writeln!(out, "/// Supplies the monitor's external variables.");
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Each method is called exactly once per step, before anything is"
    );
    let _ = writeln!(
        out,
        "/// evaluated, so two reads of one variable within a step cannot disagree."
    );
    let _ = writeln!(out, "pub trait {} {{", settings.env_trait);
    if spec.arena.externs().is_empty() {
        let _ = writeln!(
            out,
            "    // This specification reads no external variables."
        );
    }
    for (name, ty) in spec.arena.externs() {
        let _ = writeln!(out, "    /// The value of `{name}` for this step.");
        let _ = writeln!(out, "    fn {name}(&mut self) -> {};", render::ty(ty));
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn write_handler(out: &mut String, spec: &Spec, settings: &Settings) {
    let _ = writeln!(out, "/// Receives the monitor's output.");
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Triggers must be implemented; observers default to discarding their"
    );
    let _ = writeln!(out, "/// value, since observing is optional.");
    let _ = writeln!(out, "pub trait {} {{", settings.handler_trait);
    for trigger in &spec.triggers {
        let params: Vec<String> = trigger
            .args
            .iter()
            .enumerate()
            .map(|(i, arg)| format!("arg{i}: {}", render::ty(&arg.ty)))
            .collect();
        let _ = writeln!(
            out,
            "    /// Called on every step where `{}`'s guard holds.",
            trigger.name
        );
        let _ = writeln!(
            out,
            "    fn {}(&mut self{}{});",
            trigger.name,
            if params.is_empty() { "" } else { ", " },
            params.join(", ")
        );
    }
    for observer in &spec.observers {
        let _ = writeln!(out, "    /// The value of `{}` this step.", observer.name);
        let _ = writeln!(
            out,
            "    fn observe_{}(&mut self, value: {}) {{",
            observer.name,
            render::ty(&observer.ty)
        );
        let _ = writeln!(out, "        let _ = value;");
        let _ = writeln!(out, "    }}");
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn write_state(out: &mut String, spec: &Spec, settings: &Settings) {
    for stream in &spec.streams {
        let _ = writeln!(
            out,
            "/// How many values stream {} buffers.",
            stream.id.index()
        );
        let _ = writeln!(
            out,
            "pub const {}: u32 = {};",
            expr::buffer_len(stream.id),
            stream.buffer.len()
        );
    }
    let _ = writeln!(out);

    let footprint = copilot_core::resources(spec);
    let _ = writeln!(out, "/// The monitor's entire mutable state.");
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`"
    );
    let _ = writeln!(
        out,
        "/// reports this type's size as {} bytes, and `repr(Rust)` would be free to",
        footprint.state_bytes
    );
    let _ = writeln!(
        out,
        "/// reorder the fields, leaving that figure unfalsifiable."
    );
    let _ = writeln!(out, "#[repr(C)]");
    let _ = writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq)]");
    let _ = writeln!(out, "pub struct {} {{", settings.monitor);
    for stream in &spec.streams {
        let _ = writeln!(
            out,
            "    {}: [{}; {}],",
            expr::buffer(stream.id),
            render::ty(&stream.ty),
            stream.buffer.len()
        );
        if stream.needs_index() {
            let _ = writeln!(out, "    {}: u32,", expr::index(stream.id));
        }
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    let _ = writeln!(out, "impl {} {{", settings.monitor);
    let _ = writeln!(out, "    /// The monitor before its first step.");
    let _ = writeln!(out, "    pub const fn new() -> Self {{");
    let _ = writeln!(out, "        {} {{", settings.monitor);
    for stream in &spec.streams {
        let initial: Vec<String> = stream.buffer.iter().map(render::value).collect();
        let _ = writeln!(
            out,
            "            {}: [{}],",
            expr::buffer(stream.id),
            initial.join(", ")
        );
        if stream.needs_index() {
            let _ = writeln!(out, "            {}: 0,", expr::index(stream.id));
        }
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    let _ = writeln!(out, "impl Default for {} {{", settings.monitor);
    let _ = writeln!(out, "    fn default() -> Self {{");
    let _ = writeln!(out, "        Self::new()");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn write_step(out: &mut String, spec: &Spec, settings: &Settings) {
    let lowering = Lowering::new(spec, settings.index_policy, &settings.math);
    let reached = copilot_core::reachable(spec, &spec.runtime_roots());

    let _ = writeln!(out, "impl {} {{", settings.monitor);
    let _ = writeln!(out, "    /// Advances the monitor by one step.");
    let _ = writeln!(out, "    ///");
    let _ = writeln!(
        out,
        "    /// Runs in constant time and touches no memory beyond `self`: there are no"
    );
    let _ = writeln!(
        out,
        "    /// loops, no recursion, and no allocation. Every path through this function"
    );
    let _ = writeln!(out, "    /// does the same work.");
    // A specification may read nothing, or report nothing. Naming the unused
    // parameter with a leading underscore keeps generated code warning-free in
    // the user's own build, which telling their compiler to be quiet would not.
    let env_param = if spec.arena.externs().is_empty() {
        "_env"
    } else {
        "env"
    };
    let handler_param = if spec.observers.is_empty() && spec.triggers.is_empty() {
        "_handler"
    } else {
        "handler"
    };
    let _ = writeln!(
        out,
        "    pub fn {}<E: {}, H: {}>(&mut self, {env_param}: &mut E, {handler_param}: &mut H) {{",
        settings.step, settings.env_trait, settings.handler_trait
    );

    // Phase 1.
    if !spec.arena.externs().is_empty() {
        let _ = writeln!(
            out,
            "        // Phase 1: sample each external variable exactly once."
        );
        for (name, ty) in spec.arena.externs() {
            let _ = writeln!(
                out,
                "        let {}: {} = env.{name}();",
                expr::sample(name),
                render::ty(ty)
            );
        }
        let _ = writeln!(out);
    }

    // Phases 2 and 3 share one straight-line evaluation of every reachable
    // node, because both read the state as it stood at the start of the step.
    let _ = writeln!(
        out,
        "        // Phases 2 and 3: evaluate every subexpression once, reading only"
    );
    let _ = writeln!(
        out,
        "        // state committed by the previous step. Trigger arguments are computed"
    );
    let _ = writeln!(
        out,
        "        // whether or not their guard holds, which is what makes the step's"
    );
    let _ = writeln!(
        out,
        "        // timing independent of its data; expressions are pure, so this is"
    );
    let _ = writeln!(out, "        // unobservable.");
    for &id in &reached {
        let ty = spec.arena.ty_of(id);
        let _ = writeln!(
            out,
            "        let {}: {} = {};",
            expr::binding(id),
            render::ty(ty),
            lowering.node(id)
        );
    }
    let _ = writeln!(out);

    // Phase 2 output.
    if !spec.observers.is_empty() || !spec.triggers.is_empty() {
        let _ = writeln!(
            out,
            "        // Phase 2: report observers, then fire triggers."
        );
        for observer in &spec.observers {
            let _ = writeln!(
                out,
                "        handler.observe_{}({});",
                observer.name,
                expr::binding(observer.expr)
            );
        }
        for trigger in &spec.triggers {
            let args: Vec<String> = trigger
                .args
                .iter()
                .map(|arg| expr::binding(arg.expr))
                .collect();
            let _ = writeln!(
                out,
                "        if {} {{ handler.{}({}); }}",
                expr::binding(trigger.guard),
                trigger.name,
                args.join(", ")
            );
        }
        let _ = writeln!(out);
    }

    // Phase 4.
    let _ = writeln!(
        out,
        "        // Phase 4: commit. The new value overwrites the slot holding the value"
    );
    let _ = writeln!(out, "        // that has just expired.");
    for stream in &spec.streams {
        let next = expr::binding(stream.expr);
        if stream.needs_index() {
            let _ = writeln!(
                out,
                "        self.{}[self.{} as usize] = {next};",
                expr::buffer(stream.id),
                expr::index(stream.id)
            );
            let _ = writeln!(
                out,
                "        self.{} = (self.{} + 1) % {};",
                expr::index(stream.id),
                expr::index(stream.id),
                expr::buffer_len(stream.id)
            );
        } else {
            let _ = writeln!(out, "        self.{}[0] = {next};", expr::buffer(stream.id));
        }
    }

    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

type Structs = BTreeMap<String, StructType>;

/// Every struct type the specification mentions, keyed by name.
fn collect_structs(spec: &Spec) -> Result<Structs> {
    let mut found = Structs::new();

    let visit = |ty: &Type, found: &mut Structs| -> Result<()> {
        let mut stack = vec![ty.clone()];
        while let Some(ty) = stack.pop() {
            match ty {
                Type::Array { elem, .. } => stack.push(*elem),
                Type::Struct(definition) => {
                    stack.extend(definition.fields.iter().map(|(_, t)| t.clone()));
                    // Two different structs sharing a name would emit two
                    // conflicting Rust definitions.
                    if let Some(existing) = found.get(&definition.name)
                        && *existing != *definition
                    {
                        return Err(Error::ConflictingStruct(definition.name.clone()));
                    }
                    found.insert(definition.name.clone(), *definition);
                }
                _ => {}
            }
        }
        Ok(())
    };

    for id in 0..spec.arena.len() {
        visit(
            spec.arena.ty_of(copilot_core::ExprId(id as u32)),
            &mut found,
        )?;
    }
    for (_, ty) in spec.arena.externs() {
        visit(ty, &mut found)?;
    }
    for stream in &spec.streams {
        visit(&stream.ty, &mut found)?;
    }

    Ok(found)
}

/// Rejects names that would collide once the observer prefix is applied.
fn check_names(spec: &Spec) -> Result<()> {
    for trigger in &spec.triggers {
        for observer in &spec.observers {
            if trigger.name == format!("observe_{}", observer.name) {
                return Err(Error::NameCollision {
                    trigger: trigger.name.clone(),
                    observer: observer.name.clone(),
                });
            }
        }
    }
    Ok(())
}

/// Whether the specification needs anything `core` does not provide.
fn uses_math(spec: &Spec) -> bool {
    use copilot_core::{Node, Op1, Op2};
    spec.arena.nodes().any(|(_, node)| match node {
        Node::Op1(op, _) => matches!(
            op,
            Op1::Sqrt(_)
                | Op1::Exp(_)
                | Op1::Log(_)
                | Op1::Sin(_)
                | Op1::Cos(_)
                | Op1::Tan(_)
                | Op1::Asin(_)
                | Op1::Acos(_)
                | Op1::Atan(_)
                | Op1::Sinh(_)
                | Op1::Cosh(_)
                | Op1::Tanh(_)
                | Op1::Asinh(_)
                | Op1::Acosh(_)
                | Op1::Atanh(_)
                | Op1::Ceiling(_)
                | Op1::Floor(_)
        ),
        Node::Op2(op, ..) => matches!(op, Op2::Pow(_) | Op2::Logb(_) | Op2::Atan2(_)),
        _ => false,
    })
}
