//! A token-bucket rate limiter, generated by `copilot-rust`, running as real
//! axum middleware.
//!
//! ```text
//! cargo run -p copilot-example-rate-limiter
//! curl -i localhost:3000/          # repeat quickly to see 429s
//! ```
//!
//! The bucket itself is the `no_std`, allocation-free [`Monitor`] `build.rs`
//! generates from the spec next to it — the same code a bare-metal target
//! would run, with its footprint fixed by `copilot_core::resources` rather
//! than by traffic. What is not embedded-shaped is everything around it:
//! one `Monitor` per client IP, kept in a map and evicted after a period of
//! inactivity, because *how many clients exist* is not something a per-step
//! footprint claim can bound.

include!(concat!(env!("OUT_DIR"), "/monitor.rs"));

use axum::Router;
use axum::extract::{ConnectInfo, Request, State};
use axum::http::{HeaderValue, StatusCode};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use std::collections::HashMap;
use std::net::{IpAddr, SocketAddr};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

/// How long a client's bucket is kept after its last request.
const IDLE_EVICTION: Duration = Duration::from_secs(300);
/// How often the eviction sweep runs.
const EVICTION_INTERVAL: Duration = Duration::from_secs(60);

/// One client's monitor, plus the wall-clock reading `elapsed_ms` is derived
/// from — the monitor itself has no notion of real time.
struct Bucket {
    monitor: Monitor,
    last_seen: Instant,
}

#[derive(Clone)]
struct AppState {
    buckets: Arc<Mutex<HashMap<IpAddr, Bucket>>>,
}

/// Supplies `elapsed_ms` for one step from the gap since the client's last
/// request.
struct ElapsedEnv {
    elapsed_ms: f32,
}

impl Env for ElapsedEnv {
    fn elapsed_ms(&mut self) -> f32 {
        self.elapsed_ms
    }
}

/// Records what the monitor decided for this request.
#[derive(Default)]
struct Decision {
    rejected: bool,
    remaining: f32,
}

impl Handler for Decision {
    fn reject(&mut self, _available: f32) {
        self.rejected = true;
    }

    fn observe_remaining(&mut self, value: f32) {
        self.remaining = value;
    }
}

async fn rate_limit(
    State(state): State<AppState>,
    ConnectInfo(addr): ConnectInfo<SocketAddr>,
    request: Request,
    next: Next,
) -> Response {
    let now = Instant::now();

    let decision = {
        let mut buckets = state.buckets.lock().unwrap();
        let bucket = buckets.entry(addr.ip()).or_insert_with(|| Bucket {
            monitor: Monitor::new(),
            last_seen: now,
        });

        let elapsed_ms = now
            .saturating_duration_since(bucket.last_seen)
            .as_secs_f32()
            * 1000.0;
        bucket.last_seen = now;

        let mut decision = Decision::default();
        bucket
            .monitor
            .step(&mut ElapsedEnv { elapsed_ms }, &mut decision);
        decision
    };

    if decision.rejected {
        return (
            StatusCode::TOO_MANY_REQUESTS,
            [("x-ratelimit-remaining", HeaderValue::from_static("0"))],
            "rate limit exceeded\n",
        )
            .into_response();
    }

    let mut response = next.run(request).await;
    response.headers_mut().insert(
        "x-ratelimit-remaining",
        HeaderValue::from_str(&decision.remaining.floor().to_string()).unwrap(),
    );
    response
}

async fn hello() -> &'static str {
    "ok\n"
}

/// Drops buckets nobody has used in a while, so the map tracks active
/// clients rather than every client ever seen.
fn evict_idle(buckets: &Mutex<HashMap<IpAddr, Bucket>>) {
    let mut buckets = buckets.lock().unwrap();
    let now = Instant::now();
    buckets.retain(|_, bucket| now.duration_since(bucket.last_seen) < IDLE_EVICTION);
}

#[tokio::main]
async fn main() {
    let state = AppState {
        buckets: Arc::new(Mutex::new(HashMap::new())),
    };

    {
        let buckets = state.buckets.clone();
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(EVICTION_INTERVAL);
            loop {
                interval.tick().await;
                evict_idle(&buckets);
            }
        });
    }

    let app = Router::new()
        .route("/", get(hello))
        .layer(middleware::from_fn_with_state(state.clone(), rate_limit))
        .with_state(state);

    let listener = tokio::net::TcpListener::bind("127.0.0.1:3000")
        .await
        .unwrap();
    println!("listening on http://127.0.0.1:3000  (burst 20, sustained 2 req/s)");
    axum::serve(
        listener,
        app.into_make_service_with_connect_info::<SocketAddr>(),
    )
    .await
    .unwrap();
}
