// Generated by copilot-rs. Do not edit.
//
// State: 16 bytes, aligned to 4. Work per step: 11 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    // This specification reads no external variables.
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// The value of `history` this step.
    fn observe_history(&mut self, value: [u32; 3]) {
        let _ = value;
    }
    /// The value of `oldest` this step.
    fn observe_oldest(&mut self, value: u32) {
        let _ = value;
    }
    /// The value of `wrapped` this step.
    fn observe_wrapped(&mut self, value: u32) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;
/// How many values stream 1 buffers.
pub const S1_LEN: u32 = 1;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 16 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [u32; 1],
    s1: [[u32; 3]; 1],
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [0u32],
            s1: [[0u32, 0u32, 0u32]],
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, _env: &mut E, handler: &mut H) {
        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: u32 = self.s0[0];
        let e1: u32 = 1u32;
        let e2: u32 = e0.wrapping_add(e1);
        let e3: [u32; 3] = self.s1[0];
        let e4: u32 = 3u32;
        let e5: u32 = if e4 == 0 { 0u32 } else { e0.wrapping_rem(e4) };
        let e6: [u32; 3] = { let mut t = e3; t[(e5 as usize) % 3] = e0; t };
        let e7: u32 = 0u32;
        let e8: u32 = e3[(e7 as usize) % 3];
        let e9: u32 = 7u32;
        let e10: u32 = e3[(e9 as usize) % 3];

        // Phase 2: report observers, then fire triggers.
        handler.observe_history(e3);
        handler.observe_oldest(e8);
        handler.observe_wrapped(e10);

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e2;
        self.s1[0] = e6;
    }
}
