// Generated by copilot-rs. Do not edit.
//
// State: 8 bytes, aligned to 8. Work per step: 7 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    // This specification reads no external variables.
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// Called on every step where `every_third`'s guard holds.
    fn every_third(&mut self, arg0: u64);
    /// The value of `counter` this step.
    fn observe_counter(&mut self, value: u64) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 8 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [u64; 1],
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [0u64],
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, _env: &mut E, handler: &mut H) {
        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: u64 = self.s0[0];
        let e1: u64 = 1u64;
        let e2: u64 = e0.wrapping_add(e1);
        let e3: u64 = 3u64;
        let e4: u64 = if e3 == 0 { 0u64 } else { e0.wrapping_rem(e3) };
        let e5: u64 = 0u64;
        let e6: bool = e4 == e5;

        // Phase 2: report observers, then fire triggers.
        handler.observe_counter(e0);
        if e6 { handler.every_third(e0); }

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e2;
    }
}
