// Generated by copilot-rs. Do not edit.
//
// State: 24 bytes, aligned to 8. Work per step: 3 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    // This specification reads no external variables.
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// The value of `fib` this step.
    fn observe_fib(&mut self, value: u64) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 2;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 24 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [u64; 2],
    s0_idx: u32,
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [1u64, 1u64],
            s0_idx: 0,
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, _env: &mut E, handler: &mut H) {
        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: u64 = self.s0[self.s0_idx as usize];
        let e1: u64 = self.s0[((self.s0_idx + 1) % S0_LEN) as usize];
        let e2: u64 = e1.wrapping_add(e0);

        // Phase 2: report observers, then fire triggers.
        handler.observe_fib(e0);

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[self.s0_idx as usize] = e2;
        self.s0_idx = (self.s0_idx + 1) % S0_LEN;
    }
}
