// Generated by copilot-rs. Do not edit.
//
// State: 1 bytes, aligned to 1. Work per step: 17 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `temperature` for this step.
    fn temperature(&mut self) -> f32;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// Called on every step where `heat_on`'s guard holds.
    fn heat_on(&mut self, arg0: f32);
    /// Called on every step where `heat_off`'s guard holds.
    fn heat_off(&mut self, arg0: f32);
    /// The value of `celsius` this step.
    fn observe_celsius(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `heating` this step.
    fn observe_heating(&mut self, value: bool) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 1 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [bool; 1],
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [false],
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_temperature: f32 = env.temperature();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: f32 = x_temperature;
        let e1: f32 = 0.5f32;
        let e2: f32 = e0 * e1;
        let e3: f32 = 30.0f32;
        let e4: f32 = e2 - e3;
        let e5: f32 = 18.0f32;
        let e6: bool = e4 < e5;
        let e7: f32 = 21.0f32;
        let e8: bool = e4 > e7;
        let e9: bool = self.s0[0];
        let e10: bool = true;
        let e11: bool = false;
        let e12: bool = if e8 { e11 } else { e9 };
        let e13: bool = if e6 { e10 } else { e12 };
        let e14: bool = !e9;
        let e15: bool = e6 & e14;
        let e16: bool = e8 & e9;

        // Phase 2: report observers, then fire triggers.
        handler.observe_celsius(e4);
        handler.observe_heating(e9);
        if e15 { handler.heat_on(e4); }
        if e16 { handler.heat_off(e4); }

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e13;
    }
}
