// Generated by copilot-rs. Do not edit.
//
// State: 12 bytes, aligned to 4. Work per step: 55 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `armed` for this step.
    fn armed(&mut self) -> bool;
    /// The value of `fault` for this step.
    fn fault(&mut self) -> bool;
    /// The value of `s0` for this step.
    fn s0(&mut self) -> u8;
    /// The value of `s1` for this step.
    fn s1(&mut self) -> u8;
    /// The value of `s2` for this step.
    fn s2(&mut self) -> u8;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// Called on every step where `degraded`'s guard holds.
    fn degraded(&mut self, arg0: u8);
    /// The value of `reading` this step.
    fn observe_reading(&mut self, value: u8) {
        let _ = value;
    }
    /// The value of `trustworthy` this step.
    fn observe_trustworthy(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `mode` this step.
    fn observe_mode(&mut self, value: u8) {
        let _ = value;
    }
    /// The value of `was_armed` this step.
    fn observe_was_armed(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `clean_run` this step.
    fn observe_clean_run(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `since_armed` this step.
    fn observe_since_armed(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `tick` this step.
    fn observe_tick(&mut self, value: bool) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;
/// How many values stream 1 buffers.
pub const S1_LEN: u32 = 1;
/// How many values stream 2 buffers.
pub const S2_LEN: u32 = 1;
/// How many values stream 3 buffers.
pub const S3_LEN: u32 = 1;
/// How many values stream 4 buffers.
pub const S4_LEN: u32 = 4;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 12 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [u8; 1],
    s1: [bool; 1],
    s2: [bool; 1],
    s3: [bool; 1],
    s4: [bool; 4],
    s4_idx: u32,
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [0u8],
            s1: [false],
            s2: [true],
            s3: [false],
            s4: [true, false, false, false],
            s4_idx: 0,
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_armed: bool = env.armed();
        let x_fault: bool = env.fault();
        let x_s0: u8 = env.s0();
        let x_s1: u8 = env.s1();
        let x_s2: u8 = env.s2();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: bool = x_armed;
        let e1: bool = x_fault;
        let e2: u8 = x_s0;
        let e3: u8 = x_s1;
        let e4: u8 = x_s2;
        let e5: u32 = 1u32;
        let e6: u32 = 0u32;
        let e7: bool = e5 == e6;
        let e8: u8 = if e7 { e3 } else { e2 };
        let e9: bool = e3 == e2;
        let e10: bool = e7 | e9;
        let e11: u32 = e5.wrapping_add(e5);
        let e12: u32 = e5.wrapping_sub(e5);
        let e13: u32 = if e10 { e11 } else { e12 };
        let e14: bool = e13 == e6;
        let e15: u8 = if e14 { e4 } else { e8 };
        let e16: bool = e2 == e15;
        let e17: u32 = e6.wrapping_add(e5);
        let e18: u32 = if e16 { e17 } else { e6 };
        let e19: bool = e3 == e15;
        let e20: u32 = e18.wrapping_add(e5);
        let e21: u32 = if e19 { e20 } else { e18 };
        let e22: bool = e4 == e15;
        let e23: u32 = e21.wrapping_add(e5);
        let e24: u32 = if e22 { e23 } else { e21 };
        let e25: u32 = 2u32;
        let e26: u32 = e24.wrapping_mul(e25);
        let e27: u32 = 3u32;
        let e28: bool = e26 > e27;
        let e29: bool = !e0;
        let e30: bool = !e1;
        let e31: bool = e29 & e30;
        let e32: u8 = self.s0[0];
        let e33: u8 = 0u8;
        let e34: bool = e32 == e33;
        let e35: bool = e34 & e31;
        let e36: u8 = 2u8;
        let e37: u8 = if e35 { e33 } else { e36 };
        let e38: u8 = 1u8;
        let e39: bool = e32 == e38;
        let e40: bool = e39 & e30;
        let e41: u8 = if e40 { e38 } else { e37 };
        let e42: bool = e39 & e1;
        let e43: u8 = if e42 { e36 } else { e41 };
        let e44: bool = e34 & e0;
        let e45: u8 = if e44 { e38 } else { e43 };
        let e46: bool = self.s1[0];
        let e47: bool = e0 | e46;
        let e48: bool = self.s2[0];
        let e49: bool = e30 & e48;
        let e50: bool = self.s3[0];
        let e51: bool = e30 & e50;
        let e52: bool = e0 | e51;
        let e53: bool = self.s4[self.s4_idx as usize];
        let e54: bool = !e28;

        // Phase 2: report observers, then fire triggers.
        handler.observe_reading(e15);
        handler.observe_trustworthy(e28);
        handler.observe_mode(e45);
        handler.observe_was_armed(e47);
        handler.observe_clean_run(e49);
        handler.observe_since_armed(e52);
        handler.observe_tick(e53);
        if e54 { handler.degraded(e15); }

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e45;
        self.s1[0] = e47;
        self.s2[0] = e49;
        self.s3[0] = e52;
        self.s4[self.s4_idx as usize] = e53;
        self.s4_idx = (self.s4_idx + 1) % S4_LEN;
    }
}
