// Generated by copilot-rs. Do not edit.
//
// State: 0 bytes, aligned to 1. Work per step: 12 operations.
// Neither figure depends on how long the monitor has run.
//
// Requires `libm` for the transcendental functions, which `core` does not provide.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `x` for this step.
    fn x(&mut self) -> f64;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// The value of `sqrt` this step.
    fn observe_sqrt(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `floor` this step.
    fn observe_floor(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `ceil` this step.
    fn observe_ceil(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `sin` this step.
    fn observe_sin(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `exp` this step.
    fn observe_exp(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `atan2` this step.
    fn observe_atan2(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `log` this step.
    fn observe_log(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `powi` this step.
    fn observe_powi(&mut self, value: f64) {
        let _ = value;
    }
}


/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 0 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_x: f64 = env.x();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: f64 = x_x;
        let e1: f64 = libm::sqrt(e0);
        let e2: f64 = libm::floor(e0);
        let e3: f64 = libm::ceil(e0);
        let e4: f64 = libm::sin(e0);
        let e5: f64 = libm::exp(e0);
        let e6: f64 = 2.0f64;
        let e7: f64 = libm::atan2(e0, e6);
        let e8: f64 = 10.0f64;
        let e9: f64 = libm::log(e0) / libm::log(e8);
        let e10: f64 = 3.0f64;
        let e11: f64 = libm::pow(e0, e10);

        // Phase 2: report observers, then fire triggers.
        handler.observe_sqrt(e1);
        handler.observe_floor(e2);
        handler.observe_ceil(e3);
        handler.observe_sin(e4);
        handler.observe_exp(e5);
        handler.observe_atan2(e7);
        handler.observe_log(e9);
        handler.observe_powi(e11);

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
    }
}
