// Generated by copilot-rs. Do not edit.
//
// State: 0 bytes, aligned to 1. Work per step: 51 operations.
// Neither figure depends on how long the monitor has run.
//
// Requires `libm` for the transcendental functions, which `core` does not provide.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `i` for this step.
    fn i(&mut self) -> i32;
    /// The value of `j` for this step.
    fn j(&mut self) -> i32;
    /// The value of `u` for this step.
    fn u(&mut self) -> u16;
    /// The value of `v` for this step.
    fn v(&mut self) -> u16;
    /// The value of `f` for this step.
    fn f(&mut self) -> f64;
    /// The value of `h` for this step.
    fn h(&mut self) -> f64;
    /// The value of `g` for this step.
    fn g(&mut self) -> f32;
    /// The value of `p` for this step.
    fn p(&mut self) -> bool;
    /// The value of `q` for this step.
    fn q(&mut self) -> bool;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// The value of `add` this step.
    fn observe_add(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `sub` this step.
    fn observe_sub(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `mul` this step.
    fn observe_mul(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `div` this step.
    fn observe_div(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `rem` this step.
    fn observe_rem(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `neg` this step.
    fn observe_neg(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `abs` this step.
    fn observe_abs(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `signum` this step.
    fn observe_signum(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `abs_unsigned` this step.
    fn observe_abs_unsigned(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `signum_unsigned` this step.
    fn observe_signum_unsigned(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `bw_not` this step.
    fn observe_bw_not(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `bw_and` this step.
    fn observe_bw_and(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `bw_or` this step.
    fn observe_bw_or(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `bw_xor` this step.
    fn observe_bw_xor(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `shl` this step.
    fn observe_shl(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `shr` this step.
    fn observe_shr(&mut self, value: u16) {
        let _ = value;
    }
    /// The value of `cast_widen` this step.
    fn observe_cast_widen(&mut self, value: i64) {
        let _ = value;
    }
    /// The value of `cast_narrow` this step.
    fn observe_cast_narrow(&mut self, value: u8) {
        let _ = value;
    }
    /// The value of `cast_to_float` this step.
    fn observe_cast_to_float(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `fdiv` this step.
    fn observe_fdiv(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `recip` this step.
    fn observe_recip(&mut self, value: f64) {
        let _ = value;
    }
    /// The value of `f32_add` this step.
    fn observe_f32_add(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `f32_sqrt` this step.
    fn observe_f32_sqrt(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `f32_abs` this step.
    fn observe_f32_abs(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `f32_signum` this step.
    fn observe_f32_signum(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `eq` this step.
    fn observe_eq(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `ne` this step.
    fn observe_ne(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `lt` this step.
    fn observe_lt(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `le` this step.
    fn observe_le(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `gt` this step.
    fn observe_gt(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `ge` this step.
    fn observe_ge(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `float_eq` this step.
    fn observe_float_eq(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `float_le` this step.
    fn observe_float_le(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `and` this step.
    fn observe_and(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `or` this step.
    fn observe_or(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `xor` this step.
    fn observe_xor(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `not` this step.
    fn observe_not(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `implies` this step.
    fn observe_implies(&mut self, value: bool) {
        let _ = value;
    }
    /// The value of `mux` this step.
    fn observe_mux(&mut self, value: i32) {
        let _ = value;
    }
}


/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 0 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_i: i32 = env.i();
        let x_j: i32 = env.j();
        let x_u: u16 = env.u();
        let x_v: u16 = env.v();
        let x_f: f64 = env.f();
        let x_h: f64 = env.h();
        let x_g: f32 = env.g();
        let x_p: bool = env.p();
        let x_q: bool = env.q();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: i32 = x_i;
        let e1: i32 = x_j;
        let e2: u16 = x_u;
        let e3: u16 = x_v;
        let e4: f64 = x_f;
        let e5: f64 = x_h;
        let e6: f32 = x_g;
        let e7: bool = x_p;
        let e8: bool = x_q;
        let e9: i32 = e0.wrapping_add(e1);
        let e10: i32 = e0.wrapping_sub(e1);
        let e11: i32 = e0.wrapping_mul(e1);
        let e12: i32 = if e1 == 0 { 0i32 } else { e0.wrapping_div(e1) };
        let e13: i32 = if e1 == 0 { 0i32 } else { e0.wrapping_rem(e1) };
        let e14: i32 = 0i32;
        let e15: i32 = e14.wrapping_sub(e0);
        let e16: i32 = e0.wrapping_abs();
        let e17: i32 = e0.signum();
        let e18: u16 = e2;
        let e19: u16 = (e2 != 0) as u16;
        let e20: u16 = !e2;
        let e21: u16 = e2 & e3;
        let e22: u16 = e2 | e3;
        let e23: u16 = e2 ^ e3;
        let e24: u16 = if e0 as u64 >= 16 { 0u16 } else { e2.wrapping_shl(e0 as u32) };
        let e25: u16 = if e0 as u64 >= 16 { 0u16 } else { e2.wrapping_shr(e0 as u32) };
        let e26: i64 = e0 as i64;
        let e27: u8 = e0 as u8;
        let e28: f64 = e0 as f64;
        let e29: f64 = 3.0f64;
        let e30: f64 = e4 / e29;
        let e31: f64 = 1.0f64 / e4;
        let e32: f32 = 1.0f32;
        let e33: f32 = e6 + e32;
        let e34: f32 = libm::sqrtf(e6);
        let e35: f32 = e6.abs();
        let e36: f32 = e6.signum();
        let e37: bool = e0 == e1;
        let e38: bool = e0 != e1;
        let e39: bool = e0 < e1;
        let e40: bool = e0 <= e1;
        let e41: bool = e0 > e1;
        let e42: bool = e0 >= e1;
        let e43: bool = e4 == e5;
        let e44: bool = e4 <= e5;
        let e45: bool = e7 & e8;
        let e46: bool = e7 | e8;
        let e47: bool = e7 != e8;
        let e48: bool = !e7;
        let e49: bool = e48 | e8;
        let e50: i32 = if e7 { e0 } else { e1 };

        // Phase 2: report observers, then fire triggers.
        handler.observe_add(e9);
        handler.observe_sub(e10);
        handler.observe_mul(e11);
        handler.observe_div(e12);
        handler.observe_rem(e13);
        handler.observe_neg(e15);
        handler.observe_abs(e16);
        handler.observe_signum(e17);
        handler.observe_abs_unsigned(e18);
        handler.observe_signum_unsigned(e19);
        handler.observe_bw_not(e20);
        handler.observe_bw_and(e21);
        handler.observe_bw_or(e22);
        handler.observe_bw_xor(e23);
        handler.observe_shl(e24);
        handler.observe_shr(e25);
        handler.observe_cast_widen(e26);
        handler.observe_cast_narrow(e27);
        handler.observe_cast_to_float(e28);
        handler.observe_fdiv(e30);
        handler.observe_recip(e31);
        handler.observe_f32_add(e33);
        handler.observe_f32_sqrt(e34);
        handler.observe_f32_abs(e35);
        handler.observe_f32_signum(e36);
        handler.observe_eq(e37);
        handler.observe_ne(e38);
        handler.observe_lt(e39);
        handler.observe_le(e40);
        handler.observe_gt(e41);
        handler.observe_ge(e42);
        handler.observe_float_eq(e43);
        handler.observe_float_le(e44);
        handler.observe_and(e45);
        handler.observe_or(e46);
        handler.observe_xor(e47);
        handler.observe_not(e48);
        handler.observe_implies(e49);
        handler.observe_mux(e50);

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
    }
}
