// Generated by copilot-rs. Do not edit.
//
// State: 8 bytes, aligned to 4. Work per step: 10 operations.
// Neither figure depends on how long the monitor has run.
//

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Reading {
    pub altitude: f32,
    pub samples: u16,
    pub valid: bool,
}

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `sensor` for this step.
    fn sensor(&mut self) -> Reading;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// Called on every step where `lost_signal`'s guard holds.
    fn lost_signal(&mut self, arg0: f32);
    /// The value of `latest` this step.
    fn observe_latest(&mut self, value: Reading) {
        let _ = value;
    }
    /// The value of `altitude` this step.
    fn observe_altitude(&mut self, value: f32) {
        let _ = value;
    }
    /// The value of `samples` this step.
    fn observe_samples(&mut self, value: u16) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 8 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [Reading; 1],
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [Reading { altitude: 0.0f32, samples: 0u16, valid: false }],
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_sensor: Reading = env.sensor();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: Reading = x_sensor;
        let e1: Reading = self.s0[0];
        let e2: u16 = e1.samples;
        let e3: u16 = 1u16;
        let e4: u16 = e2.wrapping_add(e3);
        let e5: Reading = { let mut t = e1; t.samples = e4; t };
        let e6: bool = e0.valid;
        let e7: Reading = if e6 { e0 } else { e5 };
        let e8: f32 = e1.altitude;
        let e9: bool = !e6;

        // Phase 2: report observers, then fire triggers.
        handler.observe_latest(e1);
        handler.observe_altitude(e8);
        handler.observe_samples(e2);
        if e9 { handler.lost_signal(e8); }

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e7;
    }
}
