// Generated by copilot-rs. Do not edit.
//
// State: 8 bytes, aligned to 4. Work per step: 16 operations.
// Neither figure depends on how long the monitor has run.

/// Supplies the monitor's external variables.
///
/// Each method is called exactly once per step, before anything is
/// evaluated, so two reads of one variable within a step cannot disagree.
pub trait Env {
    /// The value of `shift` for this step.
    fn shift(&mut self) -> u32;
}

/// Receives the monitor's output.
///
/// Triggers must be implemented; observers default to discarding their
/// value, since observing is optional.
pub trait Handler {
    /// The value of `byte` this step.
    fn observe_byte(&mut self, value: u8) {
        let _ = value;
    }
    /// The value of `quotient` this step.
    fn observe_quotient(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `remainder` this step.
    fn observe_remainder(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `shifted` this step.
    fn observe_shifted(&mut self, value: u32) {
        let _ = value;
    }
    /// The value of `negated` this step.
    fn observe_negated(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `magnitude` this step.
    fn observe_magnitude(&mut self, value: i32) {
        let _ = value;
    }
    /// The value of `sign` this step.
    fn observe_sign(&mut self, value: i32) {
        let _ = value;
    }
}

/// How many values stream 0 buffers.
pub const S0_LEN: u32 = 1;
/// How many values stream 1 buffers.
pub const S1_LEN: u32 = 1;

/// The monitor's entire mutable state.
///
/// `repr(C)` is load-bearing rather than decorative: `copilot_core::resources`
/// reports this type's size as 8 bytes, and `repr(Rust)` would be free to
/// reorder the fields, leaving that figure unfalsifiable.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Monitor {
    s0: [u8; 1],
    s1: [i32; 1],
}

impl Monitor {
    /// The monitor before its first step.
    pub const fn new() -> Self {
        Monitor {
            s0: [250u8],
            s1: [3i32],
        }
    }
}

impl Default for Monitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Monitor {
    /// Advances the monitor by one step.
    ///
    /// Runs in constant time and touches no memory beyond `self`: there are no
    /// loops, no recursion, and no allocation. Every path through this function
    /// does the same work.
    pub fn step<E: Env, H: Handler>(&mut self, env: &mut E, handler: &mut H) {
        // Phase 1: sample each external variable exactly once.
        let x_shift: u32 = env.shift();

        // Phases 2 and 3: evaluate every subexpression once, reading only
        // state committed by the previous step. Trigger arguments are computed
        // whether or not their guard holds, which is what makes the step's
        // timing independent of its data; expressions are pure, so this is
        // unobservable.
        let e0: u8 = self.s0[0];
        let e1: u8 = 1u8;
        let e2: u8 = e0.wrapping_add(e1);
        let e3: i32 = self.s1[0];
        let e4: i32 = 1i32;
        let e5: i32 = e3.wrapping_sub(e4);
        let e6: u32 = x_shift;
        let e7: i32 = 100i32;
        let e8: i32 = if e3 == 0 { 0i32 } else { e7.wrapping_div(e3) };
        let e9: i32 = if e3 == 0 { 0i32 } else { e7.wrapping_rem(e3) };
        let e10: u32 = 1u32;
        let e11: u32 = if e6 as u64 >= 32 { 0u32 } else { e10.wrapping_shl(e6) };
        let e12: i32 = 0i32;
        let e13: i32 = e12.wrapping_sub(e3);
        let e14: i32 = e3.wrapping_abs();
        let e15: i32 = e3.signum();

        // Phase 2: report observers, then fire triggers.
        handler.observe_byte(e0);
        handler.observe_quotient(e8);
        handler.observe_remainder(e9);
        handler.observe_shifted(e11);
        handler.observe_negated(e13);
        handler.observe_magnitude(e14);
        handler.observe_sign(e15);

        // Phase 4: commit. The new value overwrites the slot holding the value
        // that has just expired.
        self.s0[0] = e2;
        self.s1[0] = e5;
    }
}
