//! Generating a bluesim testbench for a monitor.
//!
//! A code generator that cannot be run against the interpreter is a code
//! generator nobody can check. This emits the other half: a package that
//! instantiates the monitor, feeds it a recorded trace, and prints one line per
//! event, so a bluesim run and an interpreter run can be compared as text.

use crate::render;
use crate::{Error, Package, Result, Settings};
use copilot_core::{Spec, Type, Value};
use std::collections::BTreeMap;
use std::fmt::Write;

/// One step's worth of external variables.
pub type Row = BTreeMap<String, Value>;

/// Generates a bluesim testbench driving a monitor over a recorded trace.
///
/// The result is a package named `<Name>Sim`, holding a module `mk<Name>Sim`
/// that runs for exactly one step per row of `trace` and then calls `$finish`.
/// Compile it with `bsc -sim -u -g mk<Name>Sim <Name>Sim.bs` alongside the
/// packages [`crate::generate`] produced.
///
/// # Output format
///
/// One line per event, in the order the monitor reports them — observers first,
/// then triggers, each in declaration order:
///
/// ```text
/// OBS <observer> <value..>
/// FIRE <trigger> <argument..>
/// ```
///
/// Values are printed as whitespace-separated decimal integers, with `False`
/// and `True` as `0` and `1`. An aggregate is flattened into its scalar
/// leaves — array elements in order, struct fields in declaration order — since
/// a single line of integers is something a test can compare against the
/// interpreter without teaching it Bluespec's own formatting.
pub fn testbench(spec: &Spec, settings: &Settings, trace: &[Row]) -> Result<Package> {
    // The monitor's own checks run first, so a specification this backend
    // refuses is refused here in the same terms.
    let packages = crate::generate(spec, settings)?;
    if trace.is_empty() {
        return Err(Error::EmptyTrace);
    }

    let name = format!("{}Sim", settings.name);
    let module = format!("mk{name}");
    let mut out = String::from("-- Generated by copilot-rs. Do not edit.\n");
    let _ = writeln!(out, "--");
    let _ = writeln!(
        out,
        "-- Drives {} for {} step{}, one per cycle, and prints what it reported.",
        settings.module(),
        trace.len(),
        if trace.len() == 1 { "" } else { "s" }
    );
    let _ = writeln!(out, "package {name} where");
    let _ = writeln!(out);
    let _ = writeln!(out, "import Vector");
    let _ = writeln!(out);
    for package in &packages {
        let _ = writeln!(out, "import {}", package.name);
    }
    let _ = writeln!(out);

    write_traces(&mut out, spec, trace)?;

    let _ = writeln!(out, "{module} :: Module Empty");
    let _ = writeln!(out, "{module} =");
    let _ = writeln!(out, "  module");
    let _ = writeln!(out, "    step :: Reg (UInt 32) <- mkReg 0");
    let _ = writeln!(out);
    let _ = writeln!(out, "    let ifc :: {}", settings.interface());
    let _ = writeln!(out, "        ifc =");
    let _ = writeln!(out, "          interface {}", settings.interface());

    if spec.arena.externs().is_empty() && spec.observers.is_empty() && spec.triggers.is_empty() {
        let _ = writeln!(out, "            {{ }}");
    }
    for (variable, _) in spec.arena.externs() {
        let _ = writeln!(
            out,
            "            {variable} = return (select {} step)",
            trace_name(variable)
        );
    }
    for observer in &spec.observers {
        let leaves = leaves("v", &observer.ty);
        let _ = writeln!(
            out,
            "            observe_{} v = $display \"OBS {} {}\" {}",
            observer.name,
            observer.name,
            vec!["%d"; leaves.len()].join(" "),
            leaves.join(" ")
        );
    }
    for trigger in &spec.triggers {
        let parameters: Vec<String> = (0..trigger.args.len()).map(|i| format!("a{i}")).collect();
        let leaves: Vec<String> = trigger
            .args
            .iter()
            .zip(&parameters)
            .flat_map(|(arg, parameter)| leaves(parameter, &arg.ty))
            .collect();
        let _ = writeln!(
            out,
            "            {}{}{} = $display \"FIRE {}{}{}\"{}{}",
            trigger.name,
            if parameters.is_empty() { "" } else { " " },
            parameters.join(" "),
            trigger.name,
            if leaves.is_empty() { "" } else { " " },
            vec!["%d"; leaves.len()].join(" "),
            if leaves.is_empty() { "" } else { " " },
            leaves.join(" ")
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "    _monitor <- {} ifc", settings.module());
    let _ = writeln!(out);
    let _ = writeln!(out, "    rules");
    let _ = writeln!(out, "      \"advance\": when True ==> do");
    let _ = writeln!(out, "        step := step + 1");
    let _ = writeln!(
        out,
        "        if step == {} then $finish else noAction",
        trace.len() - 1
    );

    Ok(Package { name, source: out })
}

/// One vector per external variable, indexed by step.
fn write_traces(out: &mut String, spec: &Spec, trace: &[Row]) -> Result<()> {
    if spec.arena.externs().is_empty() {
        return Ok(());
    }
    for (variable, ty) in spec.arena.externs() {
        let name = trace_name(variable);
        let mut samples = Vec::with_capacity(trace.len());
        for (step, row) in trace.iter().enumerate() {
            let value = row.get(variable).ok_or_else(|| Error::MissingSample {
                variable: variable.clone(),
                step,
            })?;
            if !value.matches(ty) {
                return Err(Error::MissingSample {
                    variable: variable.clone(),
                    step,
                });
            }
            samples.push(value.clone());
        }
        let _ = writeln!(
            out,
            "{name} :: Vector {} {}",
            trace.len(),
            render::ty_atom(ty)
        );
        let _ = writeln!(out, "{name} = {}", render::value(&Value::Array(samples)));
        let _ = writeln!(out);
    }
    Ok(())
}

fn trace_name(variable: &str) -> String {
    format!("trace_{variable}")
}

/// Every scalar inside a value, as an expression projecting it out of `base`.
///
/// Arrays are walked in index order and structs in declaration order, which is
/// the order the interpreter's values flatten in too.
fn leaves(base: &str, ty: &Type) -> Vec<String> {
    match ty {
        Type::Array { elem, len } => (0..*len)
            .flat_map(|i| leaves(&format!("(select {base} ({i} :: UInt 32))"), elem))
            .collect(),
        Type::Struct(definition) => definition
            .fields
            .iter()
            .flat_map(|(field, field_ty)| leaves(&format!("{base}.{field}"), field_ty))
            .collect(),
        _ => vec![base.to_string()],
    }
}
