//! Differential testing over specifications nobody wrote.
//!
//! The corpus in `differential.rs` is hand-picked: it covers what a code
//! generator is *known* to get wrong. This covers the rest — random well-typed
//! specifications, generated by `copilot-gen`, compiled by `rustc`, and run
//! against the interpreter.
//!
//! Compiling has to happen at test time, since the specifications do not exist
//! until then. Every monitor goes into one file with a driver around it and is
//! compiled once, so the cost is a single `rustc` invocation rather than one per
//! specification.

mod support;

use copilot_core::{Spec, Type, Value};
use copilot_gen::{Config, Rng, spec, trace};
use copilot_interp::{Monitor, Samples};
use copilot_rust::{Settings, generate};
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

/// One generated specification and the trace to run it on.
struct Case {
    spec: Spec,
    samples: Vec<Samples>,
}

fn generate_cases(seeds: std::ops::Range<u64>, config: &Config, steps: usize) -> Vec<Case> {
    seeds
        .map(|seed| {
            let mut rng = Rng::new(seed);
            let generated = spec(&mut rng, config);
            let samples = trace(&mut rng, &generated, steps);
            Case {
                spec: generated,
                samples,
            }
        })
        .collect()
}

/// Renders a value the way the generated driver prints it, so the two can be
/// compared as text.
fn render(value: &Value) -> String {
    match value {
        Value::Bool(v) => v.to_string(),
        Value::Int8(v) => v.to_string(),
        Value::Int16(v) => v.to_string(),
        Value::Int32(v) => v.to_string(),
        Value::Int64(v) => v.to_string(),
        Value::Word8(v) => v.to_string(),
        Value::Word16(v) => v.to_string(),
        Value::Word32(v) => v.to_string(),
        Value::Word64(v) => v.to_string(),
        other => panic!("the generator does not produce {other:?} here"),
    }
}

/// A Rust literal for an external variable's sample.
fn literal(value: &Value) -> String {
    match value {
        Value::Bool(v) => v.to_string(),
        Value::Int8(v) if *v == i8::MIN => "i8::MIN".into(),
        Value::Int16(v) if *v == i16::MIN => "i16::MIN".into(),
        Value::Int32(v) if *v == i32::MIN => "i32::MIN".into(),
        Value::Int64(v) if *v == i64::MIN => "i64::MIN".into(),
        Value::Int8(v) => format!("{v}i8"),
        Value::Int16(v) => format!("{v}i16"),
        Value::Int32(v) => format!("{v}i32"),
        Value::Int64(v) => format!("{v}i64"),
        Value::Word8(v) => format!("{v}u8"),
        Value::Word16(v) => format!("{v}u16"),
        Value::Word32(v) => format!("{v}u32"),
        Value::Word64(v) => format!("{v}u64"),
        other => panic!("the generator does not produce {other:?} here"),
    }
}

fn rust_ty(ty: &Type) -> &'static str {
    match ty {
        Type::Bool => "bool",
        Type::Int8 => "i8",
        Type::Int16 => "i16",
        Type::Int32 => "i32",
        Type::Int64 => "i64",
        Type::Word8 => "u8",
        Type::Word16 => "u16",
        Type::Word32 => "u32",
        Type::Word64 => "u64",
        other => panic!("the generator does not produce {other} here"),
    }
}

/// Builds one Rust program holding every monitor and a driver that runs them.
///
/// The driver prints one line per specification per step, so the output is
/// directly comparable with what the interpreter reports.
fn build_program(cases: &[Case]) -> String {
    let mut out = String::from(
        "// Generated by copilot-rs tests. Every monitor below came from a random\n\
         // specification; the driver runs each over its own trace and prints what it\n\
         // observed.\n\n",
    );

    for (index, case) in cases.iter().enumerate() {
        let monitor = generate(&case.spec, &Settings::default())
            .unwrap_or_else(|e| panic!("case {index} must generate: {e}"));

        let _ = writeln!(out, "#[allow(dead_code)]\nmod m{index} {{");
        for line in monitor.lines() {
            let _ = writeln!(out, "    {line}");
        }
        let _ = writeln!(out, "}}\n");

        // Inputs as tables, indexed by step.
        for (name, ty) in case.spec.arena.externs() {
            let values: Vec<String> = case
                .samples
                .iter()
                .map(|sample| {
                    let mut sample = sample.clone();
                    let value = copilot_interp::Env::sample(&mut sample, name, ty)
                        .expect("the generator supplies every external variable");
                    literal(&value)
                })
                .collect();
            let _ = writeln!(
                out,
                "const IN{index}_{}: [{}; {}] = [{}];",
                name.to_uppercase(),
                rust_ty(ty),
                values.len(),
                values.join(", ")
            );
        }

        let _ = writeln!(out, "struct E{index} {{ t: usize }}");
        let _ = writeln!(out, "impl m{index}::Env for E{index} {{");
        for (name, ty) in case.spec.arena.externs() {
            let _ = writeln!(
                out,
                "    fn {name}(&mut self) -> {} {{ IN{index}_{}[self.t] }}",
                rust_ty(ty),
                name.to_uppercase()
            );
        }
        let _ = writeln!(out, "}}");

        let _ = writeln!(out, "#[derive(Default)]");
        let _ = writeln!(out, "struct H{index} {{ line: String }}");
        let _ = writeln!(out, "impl m{index}::Handler for H{index} {{");
        for observer in &case.spec.observers {
            let _ = writeln!(
                out,
                "    fn observe_{}(&mut self, value: {}) {{ \
                 self.line.push(' '); self.line.push_str(&value.to_string()); }}",
                observer.name,
                rust_ty(&observer.ty)
            );
        }
        let _ = writeln!(out, "}}\n");
    }

    let _ = writeln!(out, "fn main() {{");
    for (index, case) in cases.iter().enumerate() {
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        let mut monitor = m{index}::Monitor::new();");
        let _ = writeln!(out, "        let mut env = E{index} {{ t: 0 }};");
        let _ = writeln!(out, "        let mut handler = H{index}::default();");
        let _ = writeln!(out, "        for t in 0..{} {{", case.samples.len());
        let _ = writeln!(out, "            env.t = t;");
        let _ = writeln!(out, "            handler.line.clear();");
        let _ = writeln!(out, "            monitor.step(&mut env, &mut handler);");
        let _ = writeln!(
            out,
            "            println!(\"{index} {{t}}{{}}\", handler.line);"
        );
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
    }
    let _ = writeln!(out, "}}");
    out
}

/// What the interpreter observes, in the same line format the driver prints.
fn interpret(cases: &[Case]) -> Vec<String> {
    let mut lines = Vec::new();
    for (index, case) in cases.iter().enumerate() {
        let mut monitor = Monitor::new(&case.spec).expect("generated specs validate");
        for (step, sample) in case.samples.iter().enumerate() {
            let observed = monitor
                .step(&mut sample.clone())
                .expect("a generated spec cannot fail a step");
            let mut line = format!("{index} {step}");
            for (_, value) in &observed.observers {
                line.push(' ');
                line.push_str(&render(value));
            }
            lines.push(line);
        }
    }
    lines
}

fn compile_and_run(dir: &Path, program: &str) -> Result<Vec<String>, String> {
    std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    let source = dir.join("harness.rs");
    let binary = dir.join("harness");
    std::fs::write(&source, program).map_err(|e| e.to_string())?;

    let compile = Command::new(std::env::var("RUSTC").unwrap_or_else(|_| "rustc".into()))
        .args([
            "--edition",
            "2021",
            "-O",
            "-D",
            "warnings",
            source.to_str().unwrap(),
            "-o",
            binary.to_str().unwrap(),
        ])
        .output()
        .map_err(|e| format!("could not run rustc: {e}"))?;
    if !compile.status.success() {
        return Err(format!(
            "generated monitors did not compile:\n{}",
            String::from_utf8_lossy(&compile.stderr)
        ));
    }

    let run = Command::new(&binary)
        .output()
        .map_err(|e| format!("could not run the harness: {e}"))?;
    if !run.status.success() {
        return Err(format!(
            "the harness exited unsuccessfully:\n{}",
            String::from_utf8_lossy(&run.stderr)
        ));
    }
    Ok(String::from_utf8_lossy(&run.stdout)
        .lines()
        .map(str::to_string)
        .collect())
}

fn check(name: &str, seeds: std::ops::Range<u64>, config: &Config, steps: usize) {
    let cases = generate_cases(seeds, config, steps);
    let expected = interpret(&cases);

    let dir = std::env::temp_dir().join(format!("copilot-random-{name}-{}", std::process::id()));
    let actual = match compile_and_run(&dir, &build_program(&cases)) {
        Ok(lines) => lines,
        Err(report) => {
            let _ = std::fs::remove_dir_all(&dir);
            panic!("{report}");
        }
    };
    let _ = std::fs::remove_dir_all(&dir);

    assert_eq!(
        actual.len(),
        expected.len(),
        "the harness printed {} lines, the interpreter produced {}",
        actual.len(),
        expected.len()
    );
    for (generated, interpreted) in actual.iter().zip(&expected) {
        assert_eq!(
            generated, interpreted,
            "a generated monitor disagrees with the interpreter\n\
             (the leading number is the case index, which is also its seed)"
        );
    }
}

/// Random specifications, compiled and compared step by step.
///
/// Also a compilation test with teeth: `rustc` runs with `-D warnings`, so a
/// generated monitor that merely warns fails here. The hand-written corpus
/// cannot cover the shapes a generator stumbles into.
#[test]
fn generated_monitors_agree_with_the_interpreter() {
    check("small", 0..24, &Config::default(), 8);
}

#[test]
fn generated_monitors_agree_on_deeper_specifications() {
    let config = Config {
        streams: 5,
        externs: 4,
        depth: 6,
        max_buffer: 4,
        extra_observers: 6,
        floats: false,
    };
    check("deep", 2000..2012, &config, 12);
}
