//! Kani bisimulation harnesses for generated monitors.
//!
//! `copilot-rust` compiles a specification to a monitor built on ring buffers.
//! This crate emits a proof that the monitor implements the specification's
//! semantics — not for the handful of traces a test could try, but for every
//! reachable state and every input at once.
//!
//! # The argument
//!
//! The harness proves a **one-step bisimulation** between two things:
//!
//! - the monitor's `step`, which stores each stream as a ring buffer with a
//!   rotating index; and
//! - an independent reference `ir_step`, which stores each stream as an
//!   explicit vector in time order and reads `drop i` as a plain index into it.
//!
//! A *representation function* `abstract_state` maps the ring-buffer state to
//! the time-ordered one. The proof asserts, for an arbitrary well-formed
//! monitor state `m` and arbitrary inputs:
//!
//! ```text
//! abstract_state(step(m)) == ir_step(abstract_state(m))
//! ```
//!
//! together with the triggers and observers each produced agreeing. One-step
//! equivalence plus the representation invariant being preserved plus agreement
//! at the initial state gives full trace equivalence, by induction on steps —
//! a short pen-and-paper argument, not a machine obligation. See
//! `docs/bisimulation.md`.
//!
//! No unwinding bound is needed: `step` is loop-free by construction — const
//! array sizes, straight-line stream updates — so CBMC's unrolling is exact.
//!
//! # Why the reference is trustworthy
//!
//! A proof is only as good as what it proves the monitor equal to. Two things
//! guard the reference:
//!
//! 1. It is a *different* code generator, in a crate that does not depend on
//!    `copilot-rust`. Sharing that lowering would prove only that the generator
//!    equals itself — the trap this whole design avoids.
//! 2. It is itself differential-tested against the interpreter, exactly as the
//!    SMT encoding is (`tests/reference.rs`). So `ir_step ≈ interpreter` by
//!    testing, and `monitor ≡ ir_step` by proof, and the two compose.
//!
//! # Limits
//!
//! Transcendental functions lower to `libm` calls, which CBMC cannot see
//! through, so a specification using any of them is refused
//! ([`Error::Transcendental`]). Plain floating-point arithmetic is allowed but
//! makes CBMC much slower.

mod expr;
mod render;

use copilot_core::{Node, Op1, Op2, Spec, StructType, Type};
use expr::{Reference, binding, sample, stream_field};
use std::collections::BTreeMap;
use std::fmt::{self, Write};

/// Result alias for harness generation.
pub type Result<T> = std::result::Result<T, Error>;

/// Something that stops a specification from being verified this way.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The specification is not valid.
    Core(copilot_core::Error),
    /// It uses a transcendental function, which CBMC cannot model.
    Transcendental(&'static str),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Core(e) => e.fmt(f),
            Error::Transcendental(name) => write!(
                f,
                "`{name}` lowers to a libm call, which CBMC cannot verify through; \
                 this specification cannot be proved by bisimulation"
            ),
        }
    }
}

impl std::error::Error for Error {}

impl From<copilot_core::Error> for Error {
    fn from(e: copilot_core::Error) -> Self {
        Error::Core(e)
    }
}

/// How to name and lower the harness.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Settings {
    /// Name of the generated proof harness.
    pub harness: String,
    /// Array index policy; must match the monitor's.
    pub index_policy: copilot_core::IndexPolicy,
}

impl Default for Settings {
    fn default() -> Self {
        Settings {
            harness: "bisimulates".into(),
            index_policy: copilot_core::IndexPolicy::default(),
        }
    }
}

/// Generates a complete harness crate root.
///
/// `monitor_source` is what [`copilot_rust::generate`](../copilot_rust/fn.generate.html)
/// produced for the same specification and settings. It is taken as text rather
/// than regenerated here so that this crate need not depend on `copilot-rust` —
/// the independence the whole approach rests on.
///
/// The result compiles under ordinary `rustc` (the proof and the `Arbitrary`
/// impls are `#[cfg(kani)]`) so that the reference can be tested without a
/// verifier, and under `cargo kani`, where the proof runs.
pub fn generate_harness(spec: &Spec, monitor_source: &str, settings: &Settings) -> Result<String> {
    copilot_core::validate(spec)?;
    refuse_transcendentals(spec)?;

    let mut out = String::new();
    let _ = writeln!(out, "// Generated by copilot-verifier. Do not edit.");
    let _ = writeln!(out, "//");
    let _ = writeln!(
        out,
        "// The monitor below is verified against an independent reference by the"
    );
    let _ = writeln!(
        out,
        "// `{}` proof at the end of this file.",
        settings.harness
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "#![allow(clippy::all)]");
    let _ = writeln!(out);

    // 1. The monitor under test.
    let _ = writeln!(out, "// ===== monitor (from copilot-rust) =====");
    out.push_str(monitor_source.trim_end());
    let _ = writeln!(out, "\n");

    // 2. The independent reference.
    let _ = writeln!(out, "// ===== reference (independent lowering) =====");
    write_reference(&mut out, spec, settings);

    // 3. The proof.
    let _ = writeln!(out, "// ===== proof =====");
    write_proof(&mut out, spec, settings);

    Ok(out)
}

/// Emits the reference `State`, `ir_step`, the recorder, and the representation
/// function.
fn write_reference(out: &mut String, spec: &Spec, settings: &Settings) {
    // The time-ordered state.
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Debug)]");
    let _ = writeln!(out, "pub struct State {{");
    for stream in &spec.streams {
        let _ = writeln!(
            out,
            "    pub {}: [{}; {}],",
            stream_field(stream.id),
            render::ty(&stream.ty),
            stream.buffer.len()
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    // The initial state: the buffers as declared, which is already time-ordered.
    let _ = writeln!(out, "impl State {{");
    let _ = writeln!(out, "    pub fn initial() -> Self {{");
    let _ = writeln!(out, "        State {{");
    for stream in &spec.streams {
        let values: Vec<String> = stream.buffer.iter().map(render::value).collect();
        let _ = writeln!(
            out,
            "            {}: [{}],",
            stream_field(stream.id),
            values.join(", ")
        );
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    // What one step produces besides the next state.
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Debug, Default)]");
    let _ = writeln!(out, "pub struct Recorded {{");
    for observer in &spec.observers {
        let _ = writeln!(
            out,
            "    pub o_{}: Option<{}>,",
            observer.name,
            render::ty(&observer.ty)
        );
    }
    for trigger in &spec.triggers {
        let _ = writeln!(
            out,
            "    pub t_{}: Option<{}>,",
            trigger.name,
            arg_tuple(&trigger.args)
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    write_ir_step(out, spec, settings);
    write_recorder(out, spec);
    write_fixed_env(out, spec);
    write_abstract_state(out, spec, settings);
}

/// The reference transition: a direct denotational unfolding over the explicit
/// state vector.
fn write_ir_step(out: &mut String, spec: &Spec, settings: &Settings) {
    let reference = Reference::new(spec, settings.index_policy);

    let params: Vec<String> = spec
        .arena
        .externs()
        .iter()
        .map(|(name, ty)| format!("{}: {}", sample(name), render::ty(ty)))
        .collect();
    let _ = writeln!(
        out,
        "pub fn ir_step(state: &State{}{}) -> (State, Recorded) {{",
        if params.is_empty() { "" } else { ", " },
        params.join(", ")
    );

    // Straight-line evaluation, drops reading `state.s{k}[i]` directly.
    let mut roots = spec.runtime_roots();
    roots.sort_unstable();
    roots.dedup();
    let reachable = copilot_core::reachable(spec, &roots);
    for id in &reachable {
        let ty = spec.arena.ty_of(*id);
        let _ = writeln!(
            out,
            "    let {}: {} = {};",
            binding(*id),
            render::ty(ty),
            reference.node(*id, "state")
        );
    }

    // Observations and triggers, from the pre-step state.
    let _ = writeln!(out, "    let mut rec = Recorded::default();");
    for observer in &spec.observers {
        let _ = writeln!(
            out,
            "    rec.o_{} = Some({});",
            observer.name,
            binding(observer.expr)
        );
    }
    for trigger in &spec.triggers {
        let args: Vec<String> = trigger.args.iter().map(|arg| binding(arg.expr)).collect();
        let tuple = match args.len() {
            0 => "()".to_string(),
            1 => format!("({},)", args[0]),
            _ => format!("({})", args.join(", ")),
        };
        let _ = writeln!(
            out,
            "    if {} {{ rec.t_{} = Some({tuple}); }}",
            binding(trigger.guard),
            trigger.name
        );
    }

    // Commit: shift each vector along, appending the freshly computed value.
    // No index, no modular arithmetic — the structural opposite of the ring
    // buffer, which is exactly what the proof reconciles.
    let _ = writeln!(out, "    let next = State {{");
    for stream in &spec.streams {
        let field = stream_field(stream.id);
        let n = stream.buffer.len();
        let body = binding(stream.expr);
        if n == 1 {
            let _ = writeln!(out, "        {field}: [{body}],");
        } else {
            let kept: Vec<String> = (1..n).map(|j| format!("state.{field}[{j}]")).collect();
            let _ = writeln!(out, "        {field}: [{}, {body}],", kept.join(", "));
        }
    }
    let _ = writeln!(out, "    }};");
    let _ = writeln!(out, "    (next, rec)");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// The monitor's `Handler`, implemented to record what it is handed.
fn write_recorder(out: &mut String, spec: &Spec) {
    let _ = writeln!(out, "#[derive(Default)]");
    let _ = writeln!(out, "pub struct Recorder {{ pub rec: Recorded }}");
    let _ = writeln!(out, "impl Handler for Recorder {{");
    for observer in &spec.observers {
        let _ = writeln!(
            out,
            "    fn observe_{}(&mut self, value: {}) {{ self.rec.o_{} = Some(value); }}",
            observer.name,
            render::ty(&observer.ty),
            observer.name
        );
    }
    for trigger in &spec.triggers {
        let params: Vec<String> = trigger
            .args
            .iter()
            .enumerate()
            .map(|(i, arg)| format!("arg{i}: {}", render::ty(&arg.ty)))
            .collect();
        let names: Vec<String> = (0..trigger.args.len()).map(|i| format!("arg{i}")).collect();
        let tuple = match names.len() {
            0 => "()".to_string(),
            1 => format!("({},)", names[0]),
            _ => format!("({})", names.join(", ")),
        };
        let _ = writeln!(
            out,
            "    fn {}(&mut self{}{}) {{ self.rec.t_{} = Some({tuple}); }}",
            trigger.name,
            if params.is_empty() { "" } else { ", " },
            params.join(", "),
            trigger.name
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// The monitor's `Env`, implemented to hand back fixed samples.
fn write_fixed_env(out: &mut String, spec: &Spec) {
    let _ = writeln!(out, "pub struct FixedEnv {{");
    for (name, ty) in spec.arena.externs() {
        let _ = writeln!(out, "    pub {name}: {},", render::ty(ty));
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl Env for FixedEnv {{");
    for (name, ty) in spec.arena.externs() {
        let _ = writeln!(
            out,
            "    fn {name}(&mut self) -> {} {{ self.{name} }}",
            render::ty(ty)
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// The representation function: ring-buffer state to time-ordered state.
fn write_abstract_state(out: &mut String, spec: &Spec, _settings: &Settings) {
    let _ = writeln!(out, "pub fn abstract_state(m: &Monitor) -> State {{");
    let _ = writeln!(out, "    State {{");
    for stream in &spec.streams {
        let field = stream_field(stream.id);
        let n = stream.buffer.len();
        if n == 1 {
            // No rotating index; the single slot is already time slot 0.
            let _ = writeln!(out, "        {field}: m.{field},");
        } else {
            let len_const = format!("S{}_LEN", stream.id.0);
            let slots: Vec<String> = (0..n)
                .map(|j| format!("m.{field}[((m.{field}_idx + {j}) % {len_const}) as usize]"))
                .collect();
            let _ = writeln!(out, "        {field}: [{}],", slots.join(", "));
        }
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// The Kani proof, plus the `Arbitrary` impls it needs. Both `#[cfg(kani)]`, so
/// the rest of the file compiles under ordinary `rustc`.
fn write_proof(out: &mut String, spec: &Spec, settings: &Settings) {
    for definition in collect_structs(spec).values() {
        let _ = writeln!(out, "#[cfg(kani)]");
        let _ = writeln!(out, "impl kani::Arbitrary for {} {{", definition.name);
        let _ = writeln!(out, "    fn any() -> Self {{");
        let _ = writeln!(out, "        {} {{", definition.name);
        for (field, _) in &definition.fields {
            let _ = writeln!(out, "            {field}: kani::any(),");
        }
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "#[cfg(kani)]");
    let _ = writeln!(out, "#[kani::proof]");
    let _ = writeln!(out, "fn {}() {{", settings.harness);

    // An arbitrary monitor state, constrained only by the representation
    // invariant: every rotating index is in range.
    for stream in &spec.streams {
        let field = stream_field(stream.id);
        let _ = writeln!(
            out,
            "    let {field}: [{}; {}] = kani::any();",
            render::ty(&stream.ty),
            stream.buffer.len()
        );
        if stream.needs_index() {
            let len_const = format!("S{}_LEN", stream.id.0);
            let _ = writeln!(out, "    let {field}_idx: u32 = kani::any();");
            let _ = writeln!(out, "    kani::assume({field}_idx < {len_const});");
        }
    }
    let fields: Vec<String> = spec
        .streams
        .iter()
        .flat_map(|stream| {
            let field = stream_field(stream.id);
            if stream.needs_index() {
                vec![field.clone(), format!("{field}_idx")]
            } else {
                vec![field]
            }
        })
        .collect();
    let _ = writeln!(
        out,
        "    let mut monitor = Monitor {{ {} }};",
        fields.join(", ")
    );
    let _ = writeln!(out, "    let pre = abstract_state(&monitor);");
    let _ = writeln!(out);

    // Arbitrary inputs for this step.
    for (name, ty) in spec.arena.externs() {
        let _ = writeln!(
            out,
            "    let {}: {} = kani::any();",
            sample(name),
            render::ty(ty)
        );
    }

    let env_fields: Vec<String> = spec
        .arena
        .externs()
        .iter()
        .map(|(name, _)| format!("{name}: {}", sample(name)))
        .collect();
    let _ = writeln!(
        out,
        "    let mut env = FixedEnv {{ {} }};",
        env_fields.join(", ")
    );
    let _ = writeln!(out, "    let mut recorder = Recorder::default();");
    let _ = writeln!(out, "    monitor.step(&mut env, &mut recorder);");
    let _ = writeln!(out);

    let args: Vec<String> = spec
        .arena
        .externs()
        .iter()
        .map(|(name, _)| sample(name))
        .collect();
    let _ = writeln!(
        out,
        "    let (post, expected) = ir_step(&pre{}{});",
        if args.is_empty() { "" } else { ", " },
        args.join(", ")
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "    // The ring buffer implements the shifting window: same next state,"
    );
    let _ = writeln!(out, "    assert_eq!(abstract_state(&monitor), post);");
    let _ = writeln!(out, "    // and the same observations and triggers.");
    let _ = writeln!(out, "    assert_eq!(recorder.rec, expected);");
    let _ = writeln!(out, "}}");
}

/// The Rust type of a trigger's argument tuple.
fn arg_tuple(args: &[copilot_core::Arg]) -> String {
    match args.len() {
        0 => "()".to_string(),
        1 => format!("({},)", render::ty(&args[0].ty)),
        _ => format!(
            "({})",
            args.iter()
                .map(|a| render::ty(&a.ty))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// Every struct type the specification mentions.
fn collect_structs(spec: &Spec) -> BTreeMap<String, StructType> {
    let mut found = BTreeMap::new();
    let visit = |ty: &Type, found: &mut BTreeMap<String, StructType>| {
        let mut stack = vec![ty.clone()];
        while let Some(ty) = stack.pop() {
            match ty {
                Type::Array { elem, .. } => stack.push(*elem),
                Type::Struct(definition) => {
                    stack.extend(definition.fields.iter().map(|(_, t)| t.clone()));
                    found.insert(definition.name.clone(), *definition);
                }
                _ => {}
            }
        }
    };
    for id in 0..spec.arena.len() {
        visit(
            spec.arena.ty_of(copilot_core::ExprId(id as u32)),
            &mut found,
        );
    }
    for (_, ty) in spec.arena.externs() {
        visit(ty, &mut found);
    }
    for stream in &spec.streams {
        visit(&stream.ty, &mut found);
    }
    found
}

/// Rejects specifications whose lowering would call `libm`.
fn refuse_transcendentals(spec: &Spec) -> Result<()> {
    for (_, node) in spec.arena.nodes() {
        let name = match node {
            Node::Op1(op, _) => match op {
                Op1::Sqrt(_) => Some("sqrt"),
                Op1::Exp(_) => Some("exp"),
                Op1::Log(_) => Some("log"),
                Op1::Sin(_) => Some("sin"),
                Op1::Cos(_) => Some("cos"),
                Op1::Tan(_) => Some("tan"),
                Op1::Asin(_) => Some("asin"),
                Op1::Acos(_) => Some("acos"),
                Op1::Atan(_) => Some("atan"),
                Op1::Sinh(_) => Some("sinh"),
                Op1::Cosh(_) => Some("cosh"),
                Op1::Tanh(_) => Some("tanh"),
                Op1::Asinh(_) => Some("asinh"),
                Op1::Acosh(_) => Some("acosh"),
                Op1::Atanh(_) => Some("atanh"),
                Op1::Ceiling(_) => Some("ceil"),
                Op1::Floor(_) => Some("floor"),
                _ => None,
            },
            Node::Op2(op, ..) => match op {
                Op2::Pow(_) => Some("pow"),
                Op2::Logb(_) => Some("log"),
                Op2::Atan2(_) => Some("atan2"),
                _ => None,
            },
            _ => None,
        };
        if let Some(name) = name {
            return Err(Error::Transcendental(name));
        }
    }
    Ok(())
}
